apiVersion: v1
kind: Secret
metadata:
    name: velero-gcp-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:dQKtxp4aLql5nBxgHE9KUqmm7Hf3wTC/+x8cTwVM39Q2uRp1a8kB9vE3QWlALc2+bbqAWaDFERFedvg/aOPozaKX1Bm9XDyMkzGCpxm6mPZ3mI6FYbmBWLhR611KBGErtEEnDPe3U/VMXEdgQguWcMZ1CeCJeeXjQrV+134TAe2V6NSMJOpE+lBhCDpuxjH6fn5VMLblcttS+A+hJsHqisG9IlKIJTJ1IL/DnaHeYn0Wc1SL+4MQ2Znju1FPgtUMPZp4LzAWcY62PzIXHJR4sfKFRzKec0KL39gr5ahADqyJhK59ehkuwEvHjisdYJB74KPR5ULhMW/by6waPCP8sCohOxKvW5dZoP3jE1EBdnK5zprKHwENo01PNgYQen/djhMzmNLpJIOyZFP+xs8yXIYkNst98qOqHhdauFkdOW0Mk2owJ5pzUa1XkPJ8YWKXoBoc7SEJ1otYXANCMY3YnlECTRtnT5XV6khiBX+1UDiaRiGkRPSuqQh4iH/o5W17vIhTdjrUOqE2n6UWdJsLIZxx5xmaIR72RMrJRIbsf+zuGuYp0v2XU8MQE/Tdwh248e7eJUrTCTJRqbx/4uxNBAcnijUZOhgmZkrtra5pDncc6wFn9H7nzOBDenlYqjMQffbz2rqzHfZL8XTMZNscMUmoa/5OFPFkMhsWPdkx9fq50Nc6+mbgt9d3671xzgFLCw11brvDJOLTj5zlCNiiKw2yH3m9nD3NYsch53LVU61dGIRuBnFq61mrLNKiFwAkSiE=,iv:T5GIx6LYvTIadfhX2zn4vpW/6VX05p9V2WUXJK5iWhc=,tag:1LrTp0UGfCl5TmjvXldS8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUE9JM2FZazFIWXJwYS9O
            S2tXaG1ZU3BiRi91Umg4dkk0TlBRRWREc0M0ClJrbWxXcXNzSjhiV2MwMVBqeVds
            eXpTb0pZS0FnZGo1NWt5VlBjdUdOdWMKLS0tIEdhS215VFNaSmJYdWNDYkt5K0xu
            SVNQM3RkSjVjS0ErUVMzcGdPbmt0WEEKd+GdMGwYtUkZusCOS1ivx33liJaOti6v
            o4rtuXV0h6Wd7facEipsuOsq7y6J8qG9i8PIyZPmrHFBpZZRZ1+XWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19696wc8zkpfedtl2e82wuenpr7e86pskryzlscd69mzn9492xcms44amzd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T17:00:55Z"
    mac: ENC[AES256_GCM,data:j6P2v0nY8lYKU2bCMXhKH3xQzlQr+/THgGEAw7iAZ+Is/tdYfq3fWW3O/wPYV0whXexieNRalMIviTLV1jsYEpyCNKWjLQw+Y98mOOQ3epGVGfml+Ue188XZDs/FFzBQkZJwxzP4T8buAVoVr7LirqqQDNOu5R5UJsM4CClUgcw=,iv:o6rNo+dun3+yaPb4Cbw2l8fpLf/CJRAB69ig69dqGzA=,tag:mO9OkrjOSuK9JKtlB3wEeA==,type:str]
    version: 3.13.3
