apiVersion: v1
kind: Secret
metadata:
    name: velero-s3-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:ywQPF29iYqRrHQZ9+wcVvTF4QhSdX7nSUrWVONIyQ3HKv6EnbkYYa6Pk5vtWPUind012TlxkUIhg3KOqAwsVQ0g2CsIB3+qNKaqzNZxU/3BvH8nabvjy,iv:F8WhUDvVI/cpXNLjae+eMXWFjd+lXMLzCWVOTItpTU4=,tag:IS9/Hif+76XCBLgTViCkgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN0JPYndTNHlHeVFlT0pE
            L1hzVXVwUVUrL3o3allHUzJUSUpMeURoandRCmI1N1RRd0hXUklTNW9PL3dLYnNF
            MVlVUXMrSEZRaFRLc3V3aW8rdkFEU1UKLS0tIHc0VmlQeGM0NlFaMitqUExvRzVZ
            Q1ZWbE9yQlhaZ3dlV1RQeUFjYW8wNjAKDEOFn5DUTq9bsM8vQEDWSI9zH6e8783U
            kSRxnl2okgpNCVmKdY+Xfqah2wF3hQQeOaZZPPTc+NEFsNc7l+48tA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19696wc8zkpfedtl2e82wuenpr7e86pskryzlscd69mzn9492xcms44amzd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T15:32:40Z"
    mac: ENC[AES256_GCM,data:lB2rR+BrtUBweDKtAk9XHvD5NEum1qFmq6ftEjKcalFSuTjW5/oM3ZLp3lVu6SOvzJnUX1Ul0BAv4cwsSc8FtRMAljLvaMhYsoVLEXlN7m/OnBSLfYOtO+lfRb+HAmFoKdKTqWL1buFphLWr0GdGQL/7zTilZ4fMrIspKXISx+0=,iv:sxcwQs2M3i2R2432VUk3lZ8ekzQMZ+WB7PuJHMM+Ql0=,tag:V2Dt+S3X1+aoQgAjtD30Gg==,type:str]
    version: 3.13.3
