apiVersion: v1
kind: Service
metadata:
  name: compflow-api
  namespace: default
  labels:
    app: compflow-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: compflow-api
