apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pedrogriff/homelab-k8s-talos.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true      # Automatically removes resources deleted from Git
      selfHeal: true   # Automatically restores resources if manually changed with kubectl
    syncOptions:
    - CreateNamespace=true
