apiVersion: v1
kind: Secret
metadata:
    name: arc-github-token
    namespace: arc-runners
type: Opaque
stringData:
    github_token: ENC[AES256_GCM,data:tHz5duA0uAq+BcCEDFafPeMfBjUSLeVypA9B0YAIqmUf5kjZ7Pvb6Q==,iv:zP9LV4KxOiLYRUB0O2o/yvKIOK1exjfaxhkfheNXt+0=,tag:hs/aEhm/ZgOrg3tHe+5yhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcWRua1B3NW1VZ21RV2ls
            L2J4TG53VU1PaStDb21pRTM2TElhT3VNam1RCmdkS0lmOHJIV09Hem5TckNsTlVI
            Y3RqQjFCSUFZYW1ndmV1MHlzNjVjRW8KLS0tIEdRUzdxdnNBOWxaS0VYakZWalEv
            Nzh1bVZkRXBzWUJWS28vTy9veEdIN2sKKfIot/JRrygOh8OgigTrz8cQu2zI9ve3
            FSyodscaBjZBGzlVdrtWyv0kJMU48KrJYCilB8vPYUuWjxHG2sr3OQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19696wc8zkpfedtl2e82wuenpr7e86pskryzlscd69mzn9492xcms44amzd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T18:00:10Z"
    mac: ENC[AES256_GCM,data:Y1wj7WANiTmdOaph7Y3PWgmYxsYGkqAnbsWcjHIp+tkquyq8yK9boCCnXh/gEHFJREljjgTogs+Nk/9z2RXckh89bazO5sHVkFO0jL2Ac0mt2vbYYxwbaL30+u8XXWnJycgKtTchg8DpRDEDug3XnCxQy822CtTFoPnWghptmjQ=,iv:YtxOxlMI7/7nayeYuFXZ4WPnnoAj6mf2abp3EIgBijU=,tag:j3fbQ0D8oNJtb1BKGQ7FuA==,type:str]
    version: 3.13.3
