apiVersion: v1
kind: Secret
metadata:
    name: grafana-sso-secret
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:2BDqGrx65q+M4z/iCO4HonvjRlr2KCXlkeZluA==,iv:VC5V+eU7Qhvx1Pqzdlw0g5dCZTc0CdnpeljuJDBuvOY=,tag:0MvJOYNV/0BhCLQ6lWJJ6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bzFoSG5QZ2sxTVZGTGpU
            K29GRmptRTRoWDVxMDBwREl1MDBic3oydG1FCkhuSWkwK3VCYnp1WE9yOUJpdk1s
            cnpUNGhCcWUyZUJ1bUI3aDM0Q3MyencKLS0tIDhETjZ3R25PcFpHdGJNOWVDR3BJ
            emg4b2NkV2hJZThoM2FuM21lSWo5RGsKwXw2ZwbQvO924OAGH09iWxQ3+9uFMZ7d
            T1XSyX/UpFccY+2ptj4XxAmfEqljVLFy1T3YZTVJLhDMSJtjhSTYYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19696wc8zkpfedtl2e82wuenpr7e86pskryzlscd69mzn9492xcms44amzd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T02:57:27Z"
    mac: ENC[AES256_GCM,data:U4gaY3/B/sf0xRfLZa/Z7MQiOzc7MUE7EAEP2MT5FShb8/nbN2APIrVLhb1STjXWV/gQ0uun+h7VYtjPKp+hedVQj8GqqZNjdrVd9i5ea5/fDZva3dzxzXdkIHqgkZx0kGhtP0r0pCKjCqJ3oLwdcgW13p8HrfEL2c3+63IF2HY=,iv:todv7c9298WC/Ui36fK2oC0ZGWM+TGFb5Dpg/AN70XE=,tag:8/Itsr7tVtjZLkSKI2eIsg==,type:str]
    version: 3.13.3
