apiVersion: v1
kind: Secret
metadata:
    name: api-credentials
    namespace: default
type: Opaque
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:PmxKMeBZJAVcY7TEIIe64cmrjVJS6f6xXy4pbGyaROAZyv2odYii,iv:iTQbJ3O2ADxJ+IAuwjuyj3FKURGl+cN2mYRzJBzKlhI=,tag:v5d95Tu4vQ7HN7c8uku5RQ==,type:str]
    COMPENSATION_DB_PASSWORD: ENC[AES256_GCM,data:t+FSNf4DqB29WgBFU1r5kpWJx+qG4rEQ4d37RVC2uadC2AQcsk0=,iv:C2IV8IFC862faOfDi/H94MIWMTagadDxnbDw4uS98U4=,tag:ls8pxjomBLHCreAfx/9x0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb3F3VjcvenBibEdZUUhp
            d0dmNk9aOE5yTUFyeEYvc29MN2IxdVlTNUZZCkFHTWJnamlEejIwMFFUY1E2cUk4
            ZzFPcGNGYnppY21Eb0sxMGdFVDJQWTgKLS0tIDJMcUx1d2ZrbGhTVC9HMDRDVXBo
            bkdoTm91NjdPdjVVVm51WnJBd3VYUkkKq5AL9Ka1f6/GfTet05DYe9aXy2+Nt/8b
            7s8lNLcOmcddD8JdvlRG4a/EqLM6dq+Y7ntyMPvC68O6Kkw5tgqIuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19696wc8zkpfedtl2e82wuenpr7e86pskryzlscd69mzn9492xcms44amzd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T01:14:22Z"
    mac: ENC[AES256_GCM,data:34q+TWHs9owUnyBsqhyGcHPa7HbmVaElrAAIxeJwlZXkmZNBqgMUkaUYioen6i9s1RMW6paNG29uMxdaxeLZ96DxOlDJ1vdatojF7ke061S8h8Q8y/jNUxxIstXC7441dIwFGDROsg5KDWUmaPb1OdVtFY2/VnisPHtO9tV/2mg=,iv:Xl3Uywr3qlrQF6wo+x3JU51nZ/iCzafvRN8rzdYA5X0=,tag:ceb2n11CBhYfJFbi53KHJw==,type:str]
    version: 3.13.3
