apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-talos
  labels:
    app: hello-talos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-talos
  template:
    metadata:
      labels:
        app: hello-talos
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo:6.7.1
        ports:
        - containerPort: 9898
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: hello-talos-service
spec:
  type: NodePort
  selector:
    app: hello-talos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898
      nodePort: 30080
